// <auto-generated />
using ContactsLarsen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsLarsen.Migrations
{
    [DbContext(typeof(ContactsContext))]
    partial class ContactsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactsLarsen.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "184 S 6th St, St Helens, IA 51111",
                            Name = "Jennifer",
                            Note = "La Vie est Belle.",
                            PhoneNumber = 5158675309L
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "123 S 6th St, St Helens, IA 52222",
                            Name = "Asecond Person",
                            Note = "A second Note.",
                            PhoneNumber = 5155555555L
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "432 S 6th St, St Helens, IA 53333",
                            Name = "Athird Person",
                            Note = "Sometimes.",
                            PhoneNumber = 5155554444L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
