// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Olympics_Larsen.Models;

#nullable disable

namespace Olympics_Larsen.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Olympics_Larsen.Models.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SportID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasIndex("GameID");

                    b.HasIndex("LocationID");

                    b.HasIndex("SportID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "CAN",
                            CountryName = "Canada",
                            FlagImage = "canada.jpg",
                            GameID = "Winter",
                            LocationID = "In",
                            SportID = "Curl"
                        },
                        new
                        {
                            CountryID = "SWE",
                            CountryName = "Sweden",
                            FlagImage = "sweden.jpg",
                            GameID = "Winter",
                            LocationID = "In",
                            SportID = "Curl"
                        },
                        new
                        {
                            CountryID = "GBR",
                            CountryName = "Great Britain",
                            FlagImage = "great_britain.jpg",
                            GameID = "Winter",
                            LocationID = "In",
                            SportID = "Curl"
                        },
                        new
                        {
                            CountryID = "JAM",
                            CountryName = "Jamaica",
                            FlagImage = "jamaica.jpg",
                            GameID = "Winter",
                            LocationID = "Out",
                            SportID = "Bob"
                        },
                        new
                        {
                            CountryID = "ITA",
                            CountryName = "Italy",
                            FlagImage = "italy.jpg",
                            GameID = "Winter",
                            LocationID = "Out",
                            SportID = "Bob"
                        },
                        new
                        {
                            CountryID = "JPN",
                            CountryName = "Japan",
                            FlagImage = "japan.jpg",
                            GameID = "Winter",
                            LocationID = "Out",
                            SportID = "Bob"
                        },
                        new
                        {
                            CountryID = "DEU",
                            CountryName = "Germany",
                            FlagImage = "germany.jpg",
                            GameID = "Summer",
                            LocationID = "In",
                            SportID = "Dive"
                        },
                        new
                        {
                            CountryID = "CHN",
                            CountryName = "China",
                            FlagImage = "china.jpg",
                            GameID = "Summer",
                            LocationID = "In",
                            SportID = "Dive"
                        },
                        new
                        {
                            CountryID = "MXN",
                            CountryName = "Mexico",
                            FlagImage = "mexico.jpg",
                            GameID = "Summer",
                            LocationID = "In",
                            SportID = "Dive"
                        },
                        new
                        {
                            CountryID = "BRA",
                            CountryName = "Brazil",
                            FlagImage = "brazil.jpg",
                            GameID = "Summer",
                            LocationID = "Out",
                            SportID = "RCycle"
                        },
                        new
                        {
                            CountryID = "NLD",
                            CountryName = "Netherlands",
                            FlagImage = "netherlands.jpg",
                            GameID = "Summer",
                            LocationID = "In",
                            SportID = "Cyc"
                        },
                        new
                        {
                            CountryID = "USA",
                            CountryName = "United States of America",
                            FlagImage = "united_states.jpg",
                            GameID = "Summer",
                            LocationID = "Out",
                            SportID = "RCycle"
                        },
                        new
                        {
                            CountryID = "THA",
                            CountryName = "Thailand",
                            FlagImage = "thailand.jpg",
                            GameID = "Para",
                            LocationID = "In",
                            SportID = "Arc"
                        },
                        new
                        {
                            CountryID = "URY",
                            CountryName = "Uruguay",
                            FlagImage = "uruguay.jpg",
                            GameID = "Para",
                            LocationID = "In",
                            SportID = "Arc"
                        },
                        new
                        {
                            CountryID = "UKR",
                            CountryName = "Ukraine",
                            FlagImage = "ukraine.jpg",
                            GameID = "Para",
                            LocationID = "In",
                            SportID = "Arc"
                        },
                        new
                        {
                            CountryID = "AUT",
                            CountryName = "Austria",
                            FlagImage = "austria.jpg",
                            GameID = "Para",
                            LocationID = "Out",
                            SportID = "Can"
                        },
                        new
                        {
                            CountryID = "PAK",
                            CountryName = "Pakistan",
                            FlagImage = "pakistan.jpg",
                            GameID = "Para",
                            LocationID = "Out",
                            SportID = "Can"
                        },
                        new
                        {
                            CountryID = "ZWE",
                            CountryName = "Zimbabwe",
                            FlagImage = "zimbabwe.jpg",
                            GameID = "Para",
                            LocationID = "Out",
                            SportID = "Can"
                        },
                        new
                        {
                            CountryID = "FRA",
                            CountryName = "France",
                            FlagImage = "france.jpg",
                            GameID = "Youth",
                            LocationID = "In",
                            SportID = "Bkd"
                        },
                        new
                        {
                            CountryID = "CYP",
                            CountryName = "Cyprus",
                            FlagImage = "cyprus.jpg",
                            GameID = "Youth",
                            LocationID = "In",
                            SportID = "Bkd"
                        },
                        new
                        {
                            CountryID = "RUS",
                            CountryName = "Russia",
                            FlagImage = "russia.jpg",
                            GameID = "Youth",
                            LocationID = "In",
                            SportID = "Bkd"
                        },
                        new
                        {
                            CountryID = "FIN",
                            CountryName = "Finland",
                            FlagImage = "finland.jpg",
                            GameID = "Youth",
                            LocationID = "Out",
                            SportID = "Skt"
                        },
                        new
                        {
                            CountryID = "SVK",
                            CountryName = "Slovakia",
                            FlagImage = "slovakia.jpg",
                            GameID = "Youth",
                            LocationID = "Out",
                            SportID = "Skt"
                        },
                        new
                        {
                            CountryID = "PRT",
                            CountryName = "Portugal",
                            FlagImage = "portugal.jpg",
                            GameID = "Youth",
                            LocationID = "Out",
                            SportID = "Skt"
                        });
                });

            modelBuilder.Entity("Olympics_Larsen.Models.Game", b =>
                {
                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = "Winter",
                            GameName = "Winter Olympics"
                        },
                        new
                        {
                            GameID = "Summer",
                            GameName = "Summer Olympics"
                        },
                        new
                        {
                            GameID = "Para",
                            GameName = "Paralympics"
                        },
                        new
                        {
                            GameID = "Youth",
                            GameName = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("Olympics_Larsen.Models.Location", b =>
                {
                    b.Property<string>("LocationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = "In",
                            LocationName = "Indoor"
                        },
                        new
                        {
                            LocationID = "Out",
                            LocationName = "Outdoor"
                        });
                });

            modelBuilder.Entity("Olympics_Larsen.Models.Sport", b =>
                {
                    b.Property<string>("SportID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportID");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportID = "Curl",
                            SportName = "Curling"
                        },
                        new
                        {
                            SportID = "Bob",
                            SportName = "Bobsleigh"
                        },
                        new
                        {
                            SportID = "Dive",
                            SportName = "Diving"
                        },
                        new
                        {
                            SportID = "RCycle",
                            SportName = "Road Cycling"
                        },
                        new
                        {
                            SportID = "Cyc",
                            SportName = "Cycling"
                        },
                        new
                        {
                            SportID = "Arc",
                            SportName = "Archery"
                        },
                        new
                        {
                            SportID = "Can",
                            SportName = "Canoe Sprint"
                        },
                        new
                        {
                            SportID = "Bkd",
                            SportName = "Breakdancing"
                        },
                        new
                        {
                            SportID = "Skt",
                            SportName = "Skateboarding"
                        });
                });

            modelBuilder.Entity("Olympics_Larsen.Models.Country", b =>
                {
                    b.HasOne("Olympics_Larsen.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olympics_Larsen.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olympics_Larsen.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Location");

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
